name: Build & Publish AfterROOT Utils

on:
  push:
    branches: [ main ]
    tags:
      - v*
    paths-ignore:
      - '.idea/**'

jobs:
  build:
    name: utils-lib
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Check Out
        id: check-out
        uses: actions/checkout@v4

      - name: set up JDK
        id: setup-jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Grant execute permission for gradlew
        id: grant-execute-permissions-for-gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        id: build
        uses: gradle/gradle-build-action@v2.10.0
        env:
          CI: true
          USERNAME: ${{ secrets.GHUSERNAME }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: :lib:assemble --stacktrace

      - name: Publish with Gradle
        id: publish
        if: startsWith(github.ref, 'refs/tags/v')
        uses: gradle/gradle-build-action@v2.10.0
        env:
          CI: true
          USERNAME: ${{ secrets.GHUSERNAME }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: :lib:assemble :lib:publish --stacktrace
